---

- hosts: all
  vars: 
      gitlab_service: "https://gitlab.com"
      pipeline_id: ""
  tasks:

    - name: Create a new pipeline for Mobile IT project
      uri:
        url: "{{ gitlab_service }}/api/v4/projects/{{ gitlab_project_id }}/trigger/pipeline?token={{ gitlab_trigger_token }}&ref=main"
        method: POST
        headers:
              Content-Type: "application/json"
        body_format: json
        status_code: 201
      register: pipeline_trigger

    - name: Store pipeline id
      set_fact:
        pipeline_id: "{{ pipeline_trigger.json.id }}"

    - name: Wait for pipeline final status
      uri:
        url: "{{ gitlab_service }}/api/v4/projects/{{ gitlab_project_id }}/pipelines/{{ pipeline_id }}"
        method: GET
        headers:
              PRIVATE-TOKEN: "{{ gitlab_personal_access_token }}"
        status_code: 200
      retries: 17280
      delay: 5
      register: pipeline
      until: pipeline.json.status != 'running' and pipeline.json.status != 'pending' and pipeline.json.status != 'waiting_for_resource' and pipeline.json.status != 'preparing'
