---

- hosts: all
  vars: 
      pipeline_id: ""
  tasks:

    - name: Confirm that 503 Unavailable response is returned
      uri:
        url: "https://gitlab.com/api/v4/projects/30714152/trigger/pipeline?token=17120b92c3536102fb9c76619c9d68&ref=main"
        method: POST
        headers:
              Content-Type: "application/json"
        body_format: json
        status_code: 201
      register: pipeline_trigger
      
    - name: Set fact for subsequent job templates
      set_stats:
        data:
          pipeline_id: "{{ pipeline_trigger.json.id }}"
        
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://gitlab.com/api/v4/projects/30714152/pipelines/"{{ pipeline_id }}"
        method: GET
        headers:
              PRIVATE-TOKEN: "pC_Khq5KX7o-254x15E6"
        status_code: 200
      retries: 30
      delay: 5
      register: pipeline
 # until: pipeline.json.status != 'running'
 
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: pipeline
    
