---

- hosts: all
  tasks:
    - name: Confirm that 200 OK response is returned
      uri:
        url: "https://www.ynet.co.il/home/0,7340,L-8,00.html"
        status_code: 200
        
    - name: Confirm that 503 Unavailable response is returned
      uri:
        url: "http://ibndev003773.bpc.broadcom.net:8080/cdd/execution/00000000-0000-0000-0000-000000000000/v1/releases-execution/316/phases-execution/1757"
        method: PATCH
        headers:
              Authorization: "Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlckBjYS5jb20iLCJ0ZW5hbnRJZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsInVzZXJJZCI6MSwianRpIjoiMzY2OTkxOGUtODc2NC00YWMxLTkwMDItMjU4MzQ2ZmE5MGZlIiwiZXhwIjoxNjQyNzgxMzQzfQ.vizqh8PrDqXiUQ6i-7mF2VCiufVdGH6q_d-_KcsYDsU2tY1krvwNdlEMw8Nzf5_z7f2B7t9jPQ0l-UNYne4dYQ"
              Content-Type: "application/json"
        body_format: json
        body:
              host: '{"status":"RUNNING"}'
        status_code: 200


