- name: Hello World Sample
  hosts: all
  vars:
    message: "Hello World!"
  tasks:
    - name: with_sequence -> loop
      debug:
        msg: "{{ message }}"
      loop: "{{ range(0, 10002, 1) }}"
